HOST: http://prometheus-api.herokuapp.com/

--- Prometheus API ---

-- Exchange Resources --

List all stock exchanges
GET /exchange
< 200
< Content-Type: application/json
{
  "total_pages": 1,
  "objects": [
    {
      "commodities": [],
      "id": 1,
      "name": "New York Stock Exchange",
      "symbol": "NYSE",
      "utc_created": "2013-05-18T04:08:32.702383",
      "utc_updated": "2013-05-18T04:08:32.702432"
    }
  ],
  "num_results": 1,
  "page": 1
}

List a particular stock exchange
GET /exchange/{id}
< 200
< Content-Type: application/json
{
  "commodities": [],
  "id": 1,
  "name": "New York Stock Exchange",
  "symbol": "NYSE",
  "utc_created": "2013-05-18T04:08:32.702383",
  "utc_updated": "2013-05-18T04:08:32.702432"
}

Add new stock exchanges
POST /exchange
> Content-Type: application/json
{ "name":"New York Stock Exchange", "symbol": "NYSE" }
< 201
< Content-Type: application/json
{"id": 1}
